### ISSUE TITLE
Discord Bot Down for Remote?

### ISSUE THREAD

**Issue by BlackDahlia313** [OsmiumOP/OSM-QBUS-Scripts#1]
Since you are sunsetting, can you provide discord bot code?

Looks like your bot is offline as its not responding to any commands

**Comment by OsmiumOP** [comment]
For Exploring how the BOT worked (connecting with HTTP Wrapper), you can DM me on discord for a Command File from the BOT, but I am not sharing all the bot files as I don't want people to self host it.
My Discord : discord.io/osmfx

**Comment by BlackDahlia313** [comment]
I will reach out soon ty. Is the bot up?
