### ISSUE TITLE
carrental SCRIPT ERROR

### ISSUE THREAD

**Issue by balcer64** [OsmiumOP/OSM-QBUS-Scripts#5]
cars are parked in the parking lot, but after pressing the "E" button, they disappear

[38;5;35m[script:osm-carrental] SCRIPT ERROR: @osm-carrentals/server/server.lua:133: attempt to index a nil value (global 'ArizOP')
[38;5;35m[script:osm-carrental] SCRIPT ERROR: @osm-carrentals/server/server.lua:139: attempt to call a nil value (field 'ExecuteSql')
[38;5;35m[script:osm-carrental] > handler (@osm-carrentals/server/server.lua:27)
[38;5;35m[script:osm-carrental] SCRIPT ERROR: @osm-carrentals/server/server.lua:133: attempt to index a nil value (global 'ArizOP')
[38;5;35m[script:osm-carrental] SCRIPT ERROR: @osm-carrentals/server/server.lua:139: attempt to call a nil value (field 'ExecuteSql')
[38;5;35m[script:osm-carrental] > handler (@osm-carrentals/server/server.lua:27)
[38;5;35m[script:osm-carrental] SCRIPT ERROR: @osm-carrentals/server/server.lua:133: attempt to index a nil value (global 'ArizOP')
[38;5;35m[script:osm-carrental] SCRIPT ERROR: @osm-carrentals/server/server.lua:139: attempt to call a nil value (field 'ExecuteSql')
[38;5;35m[script:osm-carrental] > handler (@osm-carrentals/server/server.lua:27)
![1](https://user-images.githubusercontent.com/22128071/132925103-3aa12039-ed85-4bec-92f1-66fe409b3fe6.jpg)
![2](https://user-images.githubusercontent.com/22128071/132925110-1b63b292-4aae-4b9c-b50d-915541522f41.jpg)

**Comment by OsmiumOP** [comment]
Two issues
one you are using latest qbcore which the script doesn't use. 
just replace arizop with QBCore to fix the second error
